# https://aka.ms/yaml
# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'buildAndTest'
  displayName: 'Build and Test'

  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        tox.environment: 'py27'
      Python35:
        python.version: '3.5.5'
        tox.environment: 'py35'
      Python36:
        python.version: '3.6'
        tox.environment: 'py36'
      Python37:
        python.version: '3.7'
        tox.environment: 'py37'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

  - script: |
      pip install tox
      tox -e $(tox.environment)
    displayName: 'tox -e $(tox.environment)'

- job: 'createAndPublishPackage'
  displayName: 'Create and publish package'
  dependsOn: 'buildAndTest'

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: |
      pip install wheel
      python setup.py sdist
      python setup.py bdist_wheel --universal
    displayName: 'Create package'

  - bash: |
      export PACKAGE_VERSION=$(cat derpibooru/VERSION)
      echo "##vso[build.updatebuildnumber]${PACKAGE_VERSION}_${BUILD_BUILDNUMBER}"
    displayName: 'Set build number'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'package'
      targetPath: 'dist'
